
# Log level 설정
logging:
  level:
    root: info

# DB(오라클) 연동 설정
spring:
  application:
    name: mailapi
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    username: system
    password: oracle

# 쿼리를 로그로 남길 지 여부
  jpa:
    show-sql: true

# 로그에 출력되는 쿼리 포메팅
    properties:
      hibernate:
        format_sql: true

# database 초기화 여부
    hibernate:
      ddl-auto: none

# 캐시 설정 여부 false
  thymeleaf:
    cache: false

# Mail 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: mirae1296@gmail.com
    password: oltmfyjhhzjdfkby
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            
cosine:
  predict:
    server: http://127.0.0.1:8000/predict